version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./utils/initialize:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build: ./backend
    ports:
      - "3000:3000"    
    env_file:
      - .env
    volumes:
      - "./backend:/usr/src/app"
    depends_on:
      - postgres

  ui:
    image: python:3.12
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./ui:/usr/src/app"
    depends_on:
      - postgres
      - api
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

volumes:
  postgres_data: