version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./utils/initialize:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "3000:3000"    
    env_file:
      - .env
    volumes:
      - "./api:/usr/src/app"
    depends_on:
      - db

  ui:
    build: ./ui
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "./ui:/usr/src/app"
    depends_on:
      - db
      - api
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

volumes:
  postgres_data: